# Generated by Django 4.1 on 2023-01-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotogragia',
            new_name='Fotografia',
        ),
    ]
